-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 09:49:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE SGT;
USE `SGT` ;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuarios` INT(7) NOT NULL,
  `tipo_usuario` CHAR(1) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`));


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `cpf_clientes` INT(11) NOT NULL,
  `primeiro_nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `numero_casa` VARCHAR(7) NOT NULL,
  `usuarios_id_usuarios` INT(7) NOT NULL,
  PRIMARY KEY (`cpf_clientes`, `usuarios_id_usuarios`),
  INDEX `fk_clientes_usuarios1_idx` (`usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`));


-- -----------------------------------------------------
-- Table `espacos_hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espacos_hotel` (
  `id_espacos` INT(7) NOT NULL,
  `nome_espaco` VARCHAR(100) NOT NULL,
  `dia_semana_abertura` DATE NOT NULL,
  `dia_semana_fechamento` DATE NOT NULL,
  `horario_abertura` TIME NOT NULL,
  `horario_fechamento` TIME NOT NULL,
  `capacidade` INT(3) NOT NULL,
  PRIMARY KEY (`id_espacos`));


-- -----------------------------------------------------
-- Table `gerenciamento_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamento_acesso` (
  `login_cliente_id_login_cliente` INT(7) NOT NULL,
  `login_cliente_clientes_id_clientes` INT(7) NOT NULL,
  PRIMARY KEY (`login_cliente_id_login_cliente`, `login_cliente_clientes_id_clientes`));


-- -----------------------------------------------------
-- Table `funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionarios` (
  `id_funcionarios` INT(7) NOT NULL,
  `primeiro_nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `numero_casa` VARCHAR(7) NOT NULL,
  `usuarios_id_usuarios` INT(7) NOT NULL,
  PRIMARY KEY (`id_funcionarios`, `usuarios_id_usuarios`),
  INDEX `fk_funcionarios_usuarios1_idx` (`usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_funcionarios_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`));


-- -----------------------------------------------------
-- Table `reservas_espacos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservas_espacos` (
  `id_reservas` INT(7) NOT NULL,
  `dia_horario` DATETIME NOT NULL,
  `clientes_cpf_clientes` INT(11) NOT NULL,
  `espacos_hotel_id_espacos` INT(11) NOT NULL,
  PRIMARY KEY (`id_reservas`, `clientes_cpf_clientes`, `espacos_hotel_id_espacos`),
  INDEX `fk_reservas_espacos_clientes1_idx` (`clientes_cpf_clientes` ASC),
  INDEX `fk_reservas_espacos_espacos_hotel1_idx` (`espacos_hotel_id_espacos` ASC),
  CONSTRAINT `fk_reservas_espacos_clientes1`
    FOREIGN KEY (`clientes_cpf_clientes`)
    REFERENCES `clientes` (`cpf_clientes`),
  CONSTRAINT `fk_reservas_espacos_espacos_hotel1`
    FOREIGN KEY (`espacos_hotel_id_espacos`)
    REFERENCES `espacos_hotel` (`id_espacos`));


-- -----------------------------------------------------
-- Table `hospedagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospedagens` (
  `id_hospedagem` INT(7) NOT NULL,
  `checkin` DATETIME NOT NULL,
  `checkout` DATETIME NOT NULL,
  `clientes_cpf_clientes` INT(11) NOT NULL,
  PRIMARY KEY (`id_hospedagem`, `clientes_cpf_clientes`),
  INDEX `fk_reservas_clientes1_idx` (`clientes_cpf_clientes` ASC),
  CONSTRAINT `fk_reservas_clientes1`
    FOREIGN KEY (`clientes_cpf_clientes`)
    REFERENCES `clientes` (`cpf_clientes`));


-- -----------------------------------------------------
-- Table `manutencao_espaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manutencao_espaco` (
  `idlimpeza_espacos` INT NOT NULL,
  `dia` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `tipo_manutencao` CHAR(1) NOT NULL,
  `espacos_hotel_id_espacos` INT(11) NOT NULL,
  PRIMARY KEY (`idlimpeza_espacos`, `espacos_hotel_id_espacos`),
  INDEX `fk_limpeza_espacos_espacos_hotel1_idx` (`espacos_hotel_id_espacos` ASC),
  CONSTRAINT `fk_limpeza_espacos_espacos_hotel1`
    FOREIGN KEY (`espacos_hotel_id_espacos`)
    REFERENCES `espacos_hotel` (`id_espacos`));